import Head from "next/head";
import React from "react";
import Navigation from "./Navigation";

type TProps = {
  children: JSX.Element[] | JSX.Element;
  title?: string | "";
};

const AppLayout = ({ children, title }: TProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main>{children}</main>
    </>
  );
};

export default AppLayout;
